name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          jq --arg tag "$tag" '.version = $tag' dist/build/manifest.json > dist/build/manifest.tmp && mv dist/build/manifest.tmp dist/build/manifest.json

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            dist/build/main.js dist/build/manifest.json

